# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: glossary.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'glossary.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eglossary.proto\x12\x08glossary\"T\n\x04Term\x12\x0f\n\x07keyword\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x12\n\ncreated_at\x18\x03 \x01(\t\x12\x12\n\nupdated_at\x18\x04 \x01(\t\"\x12\n\x10ListTermsRequest\"2\n\x11ListTermsResponse\x12\x1d\n\x05terms\x18\x01 \x03(\x0b\x32\x0e.glossary.Term\"!\n\x0eGetTermRequest\x12\x0f\n\x07keyword\x18\x01 \x01(\t\"M\n\x0fGetTermResponse\x12\x1c\n\x04term\x18\x01 \x01(\x0b\x32\x0e.glossary.Term\x12\r\n\x05\x66ound\x18\x02 \x01(\x08\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"9\n\x11\x43reateTermRequest\x12\x0f\n\x07keyword\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"R\n\x12\x43reateTermResponse\x12\x1c\n\x04term\x18\x01 \x01(\x0b\x32\x0e.glossary.Term\x12\x0f\n\x07\x63reated\x18\x02 \x01(\x08\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"9\n\x11UpdateTermRequest\x12\x0f\n\x07keyword\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"R\n\x12UpdateTermResponse\x12\x1c\n\x04term\x18\x01 \x01(\x0b\x32\x0e.glossary.Term\x12\x0f\n\x07updated\x18\x02 \x01(\x08\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"$\n\x11\x44\x65leteTermRequest\x12\x0f\n\x07keyword\x18\x01 \x01(\t\"4\n\x12\x44\x65leteTermResponse\x12\x0f\n\x07\x64\x65leted\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t2\xeb\x02\n\x08Glossary\x12\x44\n\tListTerms\x12\x1a.glossary.ListTermsRequest\x1a\x1b.glossary.ListTermsResponse\x12>\n\x07GetTerm\x12\x18.glossary.GetTermRequest\x1a\x19.glossary.GetTermResponse\x12G\n\nCreateTerm\x12\x1b.glossary.CreateTermRequest\x1a\x1c.glossary.CreateTermResponse\x12G\n\nUpdateTerm\x12\x1b.glossary.UpdateTermRequest\x1a\x1c.glossary.UpdateTermResponse\x12G\n\nDeleteTerm\x12\x1b.glossary.DeleteTermRequest\x1a\x1c.glossary.DeleteTermResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'glossary_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TERM']._serialized_start=28
  _globals['_TERM']._serialized_end=112
  _globals['_LISTTERMSREQUEST']._serialized_start=114
  _globals['_LISTTERMSREQUEST']._serialized_end=132
  _globals['_LISTTERMSRESPONSE']._serialized_start=134
  _globals['_LISTTERMSRESPONSE']._serialized_end=184
  _globals['_GETTERMREQUEST']._serialized_start=186
  _globals['_GETTERMREQUEST']._serialized_end=219
  _globals['_GETTERMRESPONSE']._serialized_start=221
  _globals['_GETTERMRESPONSE']._serialized_end=298
  _globals['_CREATETERMREQUEST']._serialized_start=300
  _globals['_CREATETERMREQUEST']._serialized_end=357
  _globals['_CREATETERMRESPONSE']._serialized_start=359
  _globals['_CREATETERMRESPONSE']._serialized_end=441
  _globals['_UPDATETERMREQUEST']._serialized_start=443
  _globals['_UPDATETERMREQUEST']._serialized_end=500
  _globals['_UPDATETERMRESPONSE']._serialized_start=502
  _globals['_UPDATETERMRESPONSE']._serialized_end=584
  _globals['_DELETETERMREQUEST']._serialized_start=586
  _globals['_DELETETERMREQUEST']._serialized_end=622
  _globals['_DELETETERMRESPONSE']._serialized_start=624
  _globals['_DELETETERMRESPONSE']._serialized_end=676
  _globals['_GLOSSARY']._serialized_start=679
  _globals['_GLOSSARY']._serialized_end=1042
# @@protoc_insertion_point(module_scope)
